<a href="https://colab.research.google.com/github/JvNeo/Estudos-Python/blob/main/Inicio_Analise_de_dados_(Excercicios_e_pr%C3%A1ticas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prárica: "O Estagiário de Dados" (Exercicio proposto pela inteligencia artificial Gemini)

Para fixar o conteúdo do artigo, preparei 3 exercícios simulando problemas reais (mas simplificados) que você encontraria.

Abra seu Google Colab (ou editor preferido), tente resolver e cole sua resposta aqui ou me diga se tiver dúvidas.


---

**Exercício 1**: A Lista de Vendas (Listas e Mutabilidade)
Você tem uma lista de vendas de uma loja, mas percebeu que o último valor está errado.

1. Crie uma lista chamada vendas com os valores: [100, 150, 1500, 200].

2. O valor 1500 foi um erro de digitação, deveria ser 150. Altere esse valor específico acessando a lista pelo índice (lembre-se que o índice começa em 0).

3. Imprima a lista corrigida.

---

**Exercício 2**: O Cadastro (Dicionários)
Você precisa criar um registro simples de um produto.

1. Crie um dicionário chamado produto com as chaves: 'nome', 'preco' e 'disponivel'.

2. Atribua valores a eles (use uma string para o nome, float para o preço e bool para disponível).

3. Imprima o tipo (type) da chave 'preco'.

---

**Exercício 3**: Limpeza de Dados (Casting/Conversão)
Você recebeu dois valores via formulário, mas eles vieram como texto (String). Você precisa somá-los.

1. Crie duas variáveis: valor_1 = "25.50" e valor_2 = "14.50" (note as aspas, indicando que são texto).

2. Tente somar as duas diretamente e veja o que acontece (vai concatenar/juntar o texto).

3. Agora, faça a conversão (casting) de ambas para float, some os resultados matematicamente e imprima o valor final (que deve ser 40.0).

---

In [ ]:
# EXERCÍCIO 1

# Atribuição dos valores a variável vendas
vendas = [100, 150, 1500, 200]
# Alteração do valor no indice 2 que é 1500 para o valor correto 150
vendas[2] = 150
# Verificação da alteração
vendas

[100, 150, 150, 200]

In [ ]:
# EXERCÍCIO 2
# Criação da variávei e inclusas dos tipos string, float e boolean
produto = {'nome':"Jogo",
           'preco':299.90,
           'disponivel':True}
# Verificação do tipo
print(type(produto['preco']))

<class 'float'>


In [ ]:
# EXERCÍCIO 3

# Atribuição dos valores no tipo string
valor_1 = "25.50"
valor_2 = "14.50"
# Verificação de soma onde o resultado será 25.5014.50
valor_1 + valor_2
# Alterção das variaveis para o tipo Float
valor_1 = float(valor_1)
valor_2 = float(valor_2)
# Verificação se a soma ocorre normalmente
valor_1 + valor_2

40.0

# 🏋️‍♀️ Exercícios de Fixação

Vamos sair do exemplo da "média escolar" e aplicar isso em cenários de Análise de Dados (imagine que você está limpando uma base de dados).

---

**Exercício 1**: Verificação de Frete (if/else)
Em muitas lojas, o frete é grátis se a compra for alta.

- Crie uma variável valor_compra com o valor 150.00.
- Crie uma lógica:
- Se (if) a compra for maior ou igual a 200.00, imprima "Frete Grátis".
- Senão (else), imprima "Frete: R$ 15,00".
- Teste mudando o valor da variável para ver as duas mensagens.

---

**Exercício 2**: Classificação de Risco (if/elif/else)
Um banco classifica clientes baseado no Score de Crédito.

- Crie uma variável score com valor 750.
- Crie a seguinte lógica de classificação:
- Se o score for menor que 300: imprima "Risco Alto".
- Senão se (elif) o score for menor que 700: imprima "Risco Médio".
- Senão (else - ou seja, 700 ou mais): imprima "Risco Baixo".

---

**Exercício 3**: Correção de Lógica (Atenção ao detalhe)
No texto que você leu, a condição do elif estava escrita de forma lógica, mas incompleta para o Python (elif media > 5 media < 7). No Python, precisamos usar o conector and.
- Tarefa: Crie um sistema que verifica a temperatura de uma máquina (servidor).
- temperatura = 45
- Se temperatura < 40: imprima "Normal".
- Se temperatura for maior ou igual a 40 E (and) menor que 60: imprima "Atenção: Aquecendo".

**Dica**: Escreva elif temperatura >= 40 and temperatura < 60:

Senão: imprima "Perigo: Superaquecimento".

---

In [ ]:
# EXCERCÍCIO 1

# Atribuição da variavel
valor_compra = 150.00
if valor_compra >= 200.00:  # Condição se valor_compra foir maior ou igual 200
  print("Frete Grátis")
else:                       # Condição else se a primeira condição for falsa
  print("Frete: RS 15,00")

Frete: RS 15,00


In [ ]:
# EXERCÍCIO 2

# Atribuição da variavel
score = 750
if score < 300:
  print("Risco Alto")
elif score < 700:
  print("Risco Médio")
else:
  print("Risco Baixo")

Risco Baixo


In [ ]:
# EXERCÍCIO 3

# Atribuição da variavel
temperatura = 45
if temperatura < 40:
  print("Normal")
elif temperatura >= 40 and temperatura < 60:
  print("Atenção: Aquecendo")
else:
  print("Perigo: Superaquecimento")

Atenção: Aquecendo


# Exercícios de Match/Case

---

**Exercício 1:** Tratamento de Erros (Web Scraping)
Na análise de dados, frequentemente raspamos dados da internet. Os servidores retornam códigos (200 = OK, 404 = Não encontrado, 500 = Erro no servidor).

- Crie uma variável codigo_erro = 404.
- Use match codigo_erro:
- case 200: imprima "Sucesso: Dados coletados".
- case 404: imprima "Erro: Página não encontrada".
- case 500: imprima "Erro: Servidor indisponível".
- case _: (o caso padrão): imprima "Erro desconhecido".

---

**Exercício 2:** Categorização de Clientes (Com Guard Clauses)
Vamos refazer uma lógica parecida com a da média escolar, mas para Score de Crédito (semelhante ao exercício anterior de if, mas usando a sintaxe nova).

- Crie score = 800.
- Use match score:
- case score if score < 300: imprima "Recusado".
- case score if 300 <= score < 700: imprima "Em análise".
- case score if score >= 700: imprima "Aprovado com Crédito".

`Obs: Note que no Exercício 2, como estamos comparando números (maior/menor), precisamos repetir o nome da variável (case score if score < 300). No Exercício 1, como é o valor exato, basta colocar o número (case 200).`

In [ ]:
# EXERCICÍO 1

codigo_erro = 300 # Atribuição da variável

match codigo_erro:  # Criação do comando match
  case 200: # Primeiro teste lógico do case
    print("Sucesso: Dados coletados")
  case 404: # Segundo teste lógico do case
    print("Erro: Página não encontrada")
  case 500: # Terceiro teste lógico do cas
    print("Erro: Servidor indisponível")
  case _: # Ultimo teste lógico do case caso nenhuma outro teste lógico tenha sido efetuado
    print("Erro desconhecico")

Erro desconhecico


In [ ]:
# EXERCICÍO 2

score = 80 # Atribuição da variável

match score:  # Criação do comando match
  case score if score < 300:  # Primeiro teste lógico, verificando se o score é menor que 300
    print("Recusado")
  case score if 300 <= score < 700:  # Segundo teste lógico, verificando se 300 é menor ou igual ao score e score é menor que 700
    print("Em análise")
  case score if score >= 700:  # Terceiro teste lógico, verificando se o score é maior ou igual que 700
    print("Aprovado com Crédito")

# IF e WHILE

Vamos fazer dois exercícios focados nessas diferenças.

**Exercício 1**: A Lista de Preços (for)
Você tem uma lista de preços e quer aplicar um desconto de 10% em todos eles para ver como ficaria.

- Crie uma lista: precos = [100, 200, 500]

- Crie um for que passe por cada preco na lista.

- Dentro do loop, imprima o preço com desconto (multiplique por 0.9).

---

**Exercício 2**: A Meta de Vendas (while)
Você quer simular quanto tempo leva para bater uma meta acumulada.

- Crie uma variável total_vendas = 0.

- Crie um loop while que rode enquanto total_vendas for menor que 1000.

- Dentro do loop:

- Adicione um valor fixo (ex: total_vendas = total_vendas + 100).

- Imprima o valor atual: print("Venda processada. Total:", total_vendas).

In [3]:
# EXERCICIO 1

precos = [100, 200, 500] # Criação da Váriavel

for i in precos: # Inicio do 'for', indicando que 'i' seria a representação de cada item
  print("Com descontos os preços ficam", i * 0.9) # print com texto e multiplicação por 'i', representando que cada 'i'(item) será multiplicado por 0.9 e terá como saida um texto

Com descontos os preços ficam 90.0
Com descontos os preços ficam 180.0
Com descontos os preços ficam 450.0


In [7]:
# EXERCICIO 2

total_vendas = 0 # Criação da Váriavel

while total_vendas < 1000: # Inicio do While, perguntando "enquanto total_vendas for menor que 1000"
  total_vendas = total_vendas + 100 # Resposta do While, total_vendas será iguál a total_vendas + 100
  print("Venda processada. Total:", total_vendas) # Print representado para quando o While finalizar, quando teste anterior chegar a 1000, o while se encerra e o print anunciando que o total chegou a igual ou ultrapassou 1000

Venda processada. Total: 100
Venda processada. Total: 200
Venda processada. Total: 300
Venda processada. Total: 400
Venda processada. Total: 500
Venda processada. Total: 600
Venda processada. Total: 700
Venda processada. Total: 800
Venda processada. Total: 900
Venda processada. Total: 1000
